### ISSUE TITLE
Contradictory descriptions of obvious and non-obvious changes

### ISSUE THREAD

**Issue by wilkinsona** [spring-attic/pivotal-cla#129]
https://cla.pivotal.io/about#obvious-fixes

Listed as obvious (emphasis mine):

> **Refactoring** a source file into multiple source files or consolidating multiple source files a single source file without changing functionality

Listed as non-obvious (emphasis mine):

> A translation or **refactor**

**Comment by Shredder121** [comment]
Probably the first `Refactoring` should be more like `Splitting`/`Dividing`, since that's a specific 'refactoring'?
Maybe a word that fits with `consolidating` in that same sentence?

Although maybe, the `....without changing functionality` is already hinting at specific refactorings.

The non-obvious list could maybe also benefit from using the same way of phrasing.

**Comment by rwinch** [comment]
@wilkinsona Thanks for bringing this up. I copy pasted the wording from legal, so I will have to run it by them.
